import { StyleSheet } from 'react-native';

import { a11y } from '../../../theme/a11y';
import { colors } from '../../../theme/colors';
import { spacing } from '../../../theme/spacing';
import { typography } from '../../../theme/typography';

export const drawResultStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.softCream },
  gradient: { flex: 1 },
  container: {
    paddingHorizontal: spacing.screenPadding,
    paddingTop: spacing.md,
    paddingBottom: spacing.xl,
  },
  stateWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.screenPadding,
  },
  stateTitle: {
    color: colors.inkSoft,
    fontSize: typography.title2,
    lineHeight: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  stateBody: {
    marginTop: spacing.xs,
    color: colors.inkMuted,
    fontSize: typography.bodySmall,
    lineHeight: 18,
    textAlign: 'center',
  },

  registerPill: {
    position: 'absolute',
    top: 56,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: colors.softMist,
    borderRadius: 999,
    zIndex: 20,
    shadowColor: 'rgba(58,35,5,0.32)',
    shadowOpacity: 0.5,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  registerIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.pokeBlueFaint,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  registerIconText: {
    fontSize: 13,
  },
  registerText: {
    color: colors.inkSoft,
    fontSize: typography.bodySmall,
    fontWeight: '900',
  },

  header: {
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  headerTitle: {
    color: colors.inkSoft,
    fontSize: typography.title2,
    fontWeight: '900',
  },
  collectionBar: {
    marginTop: 6,
    alignSelf: 'center',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: colors.softMist,
    shadowColor: colors.shadowSoft,
    shadowOpacity: 1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  collectionText: {
    color: colors.inkSoft,
    fontSize: typography.caption,
    fontWeight: '900',
    letterSpacing: 0.4,
  },

  featuredHaloWrap: {
    marginTop: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  featuredHalo: {
    position: 'absolute',
    width: 360,
    height: 360,
    borderRadius: 360,
    top: -50,
  },
  featured: {
    width: '100%',
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: 'rgba(58,35,5,0.32)',
    shadowOpacity: 0.6,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  featuredGradient: {
    minHeight: 230,
    padding: spacing.md,
    justifyContent: 'flex-end',
    borderRadius: 24,
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.6)',
  },
  newBadgeWrap: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
  },
  newBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: colors.danger,
    shadowColor: 'rgba(209,75,75,0.6)',
    shadowOpacity: 1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  newBadgeText: {
    color: colors.softCream,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  featuredRarityChip: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginBottom: 6,
  },
  featuredRarity: {
    color: colors.softCream,
    fontSize: typography.caption,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  featuredQuestionSlab: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  featuredQuestion: {
    color: colors.inkSoft,
    fontSize: typography.title3,
    lineHeight: 24,
    fontWeight: '900',
  },
  featuredShine: {
    position: 'absolute',
    top: -20,
    left: -40,
    width: 80,
    height: 280,
    backgroundColor: 'rgba(255,255,255,0.3)',
    transform: [{ rotate: '18deg' }],
  },

  summaryStrip: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    justifyContent: 'center',
  },
  summaryChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  summaryChipLeg: { backgroundColor: colors.rarityLegendary },
  summaryChipRar: { backgroundColor: colors.rarityRare },
  summaryChipCom: { backgroundColor: colors.rarityCommon },
  summaryChipText: {
    color: colors.softCream,
    fontSize: typography.caption,
    fontWeight: '900',
    letterSpacing: 0.4,
  },

  sheetToggleButton: {
    marginTop: spacing.md,
    minHeight: a11y.minTouch,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.hairline,
    backgroundColor: colors.softMist,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  sheetToggleText: {
    color: colors.inkSoft,
    fontSize: typography.bodySmall,
    fontWeight: '800',
  },

  sheetWrap: {
    marginTop: spacing.sm,
    borderRadius: spacing.cardRadius,
    backgroundColor: colors.softMist,
    padding: spacing.sm,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    shadowColor: colors.shadowSoft,
    shadowOpacity: 1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  gridCard: {
    width: '48%',
    minHeight: 120,
    borderRadius: 14,
    backgroundColor: colors.softCream,
    padding: spacing.sm,
    marginBottom: spacing.xs,
    borderWidth: 1,
    borderColor: colors.hairline,
    overflow: 'hidden',
  },
  gridSlotNumber: {
    position: 'absolute',
    top: 6,
    left: 8,
    color: colors.inkMuted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  gridRarityDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
  },
  gridRarityDotText: {
    color: colors.softCream,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  gridBody: {
    marginTop: 22,
  },
  gridTag: {
    color: colors.inkMuted,
    fontSize: typography.caption,
    fontWeight: '700',
    marginBottom: 4,
  },
  gridQuestion: {
    color: colors.inkSoft,
    fontSize: typography.bodySmall,
    lineHeight: 18,
    fontWeight: '700',
  },
  gridNewRibbon: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  gridNewRibbonText: {
    color: colors.softCream,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.4,
  },

  footer: {
    marginTop: spacing.md,
  },
  primaryCta: {
    minHeight: 56,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    backgroundColor: colors.pokeBlue,
    shadowColor: 'rgba(44,156,192,0.5)',
    shadowOpacity: 1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  primaryCtaText: {
    color: colors.softCream,
    fontSize: typography.button,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  doneLink: {
    marginTop: spacing.sm,
    minHeight: a11y.minTouch,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneText: {
    color: colors.inkMuted,
    fontSize: typography.bodySmall,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },

  confetti: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.06,
    backgroundColor: colors.glowGold,
  },

  modalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: spacing.lg,
  },
  modalCard: {
    width: '100%',
    borderRadius: spacing.cardRadius,
    backgroundColor: colors.softMist,
    padding: spacing.md,
    shadowColor: 'rgba(0,0,0,0.4)',
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  modalRarityChip: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  modalRarity: {
    color: colors.softCream,
    fontSize: typography.caption,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  modalTitle: {
    marginTop: spacing.sm,
    color: colors.inkSoft,
    fontSize: typography.title3,
    lineHeight: 24,
    fontWeight: '900',
    marginBottom: spacing.md,
  },
  pressed: { opacity: 0.9 },
});
