<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Authoring.Application\Authoring.Application.csproj" />
    <ProjectReference Include="..\Authoring.Domain\Authoring.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Infrastructure.Core\Infrastructure.Core.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
