<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.0" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RecallSmith.Lambda.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RecallSmith.Lambda.Common\RecallSmith.Lambda.Common.csproj" />
  </ItemGroup>

</Project>
