#!/usr/bin/env bash
# P03 verify (r26). Generated by plan-to-wave.py from the plan; edit the plan, not this file.
# cwd = issue worktree; the driver exports BASE.
TAG=P03; export FROZEN_FILES='mobile/src/content/deckRepository.ts mobile/src/sync/progressSync.ts mobile/src/review/model.ts' OTA_SAFE_PATHS='mobile/package.json mobile/package-lock.json mobile/app.json mobile/eas.json' OTA_NATIVE_RE='^mobile/(ios|android)/' PAID_MODEL_RE='api\.anthropic\.com|anthropic\.Anthropic\(|bedrock-runtime|api\.openai\.com'
source /Users/qc/.claude/skills/dynamic-delivery-workflow/scripts/verify-lib.sh

step "1 guards (scope, frozen, OTA-safe, suppressions, secrets)"
require_scope \
  'infra/.*' \
  'docs/delivery/r26-issues/P03-.*' \
  'docs/delivery/r26-issues/P03\..*'
require_frozen
require_ota_safe
require_no_suppressions
require_no_secrets ':(exclude)evals/reports/**'

step "2 deliverables"
require_changed docs/delivery/r26-issues/P03-notes.md
require_file docs/delivery/r26-issues/P03.plan-allow.json
forbid_grep infra/modules/identity/main.tf 'aws_iam_role" "snowflake"' 'Snowflake role still defined'

step "3 targeted tests"
run_cmd 'targeted tests failed' bash -c 'terraform fmt -check -recursive infra && terraform -chdir=infra/envs/prod init -backend=false -input=false -lockfile=readonly >/dev/null && terraform -chdir=infra/envs/prod validate && python3 infra/scripts/check-agent-routes.py'

echo "P03 VERIFY OK"
